### ISSUE TITLE
Option to disable internal tagging

### ISSUE THREAD

**Issue by jayvdb** [oxidecomputer/typify#264]
https://serde.rs/enum-representations.html#internally-tagged

Internal tagging has a side-effect that I need to avoid, and it would be great if it could be disabled in the `TypeSpaceSettings`.

I have a `oneOf` that looks like
```yaml
    ReportData:
      oneOf:
        - $ref: "./ReportType1.yaml#/components/schemas/ReportType1"
        - $ref: "./ReportType2.yaml#/components/schemas/ReportType2"
        - $ref: "./ReportType3.yaml#/components/schemas/ReportType3"
        - $ref: "./ReportType4.yaml#/components/schemas/ReportType4"
```

each of them looks like
```
    ReportType1:
      type: object
      required:
        - report_type
        - other
        - stuff
      properties:
        report_type:
          type: string
          default: type1
          enum:
            - type1
        ...
```

This generates
```rust
    #[serde(tag = "report_type")]
    pub enum ReportData {
        #[serde(rename = "type1")]
        ReportType1 { .. },
        #[serde(rename = "type2")]
        ReportType2 { ...  },
        #[serde(rename = "type3")]
        ReportType3 {  ... },
        #[serde(rename = "type4")]
        ReportType4 { ... },
    }
```

The problem is that all of the members of `ReportType1` are inlined into the enum variant, except for the `report_type` member. Likewise for `ReportType2`, etc.  i.e. the enum does *not* refer to the struct for `ReportType1`, but it instead creates a enum variant that is similar but omits the `report_type` field.

I appreciate this is appropriate for many usages, but we would prefer to have the enum variants use the described types as-is, without internal tagging, knowing the negatives of external tagging.

Is there is something already which allows control of this? (`with_struct_builder` looks interesting..).  If not, what would be the desirable approach to allow this, so we can build it in an acceptable/mergable PR.
