### ISSUE TITLE
parameters that are not required and nullable cannot be set to null

### ISSUE THREAD

**Issue by mat813** [oxidecomputer/typify#851]
I have this schema, there are no required attributes (because it's used to patch an entry, so you can update only one element), there are so much more properties, but these two show what I mean (taken from netbox's openapi definition, which you probably cannot find online because it's auto-generated from the code at runtime) :

```yaml
components:
  schemas:
    PatchedWritableInterfaceRequest:
      type: object
      description: Adds support for custom fields and tags.
      properties:
        device:
          type: integer
        lag:
          type: integer
          nullable: true
          title: Parent LAG
```

And the type for this is with the latest commit (7510faf9) from main :

```rust
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, PartialEq)]
    pub struct PatchedWritableInterfaceRequest {
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub device: ::std::option::Option<i64>,
        #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
        pub lag: ::std::option::Option<i64>,
    }
```

With this, I cannot make a request with `{lag:null}`.
It feels like that if a property is not required, it ends up being an `Option<T>`, and that a property being nullable also ends up being an `Option<T>`.
A property that is not required and nullable should probably be an `Option<Option<T>>` so that it can be:

- unset (which would be `None`)
- set to null, which would be `Some(None)`
- set to a value would be `Some(Some(123))`.

For reference (and why I hve a PartialEq), the build.rs code for this is:

```rust
    let mut settings = GenerationSettings::new();
    settings.with_interface(InterfaceStyle::Builder);
    settings
        .with_derive("PartialEq")
        .with_pre_hook(quote! { |request| tracing::trace!("request {:?}", request) })
        .with_post_hook(quote! { |result| tracing::trace!("result {:?}", result) });

    let mut generator = Generator::new(&settings);

    let tokens = generator.generate_tokens(&spec)?;
    let ast = parse2(tokens)?;
```
